### ISSUE TITLE
Crash reports

### ISSUE THREAD

**Issue by gingerbeardman** [otzbergnet/wbmExtension#26] opened 2020-01-27 16:07 UTC
I seem to be getting one of these every time I use it?

Here's a bunch: [Archive.zip](https://github.com/otzbergnet/wbmExtension/files/4118021/Archive.zip)

edit: Actually, other Safari Extensions are producing similar crash logs.

**Comment by otzbergnet** [comment] 2020-01-27 17:53
I take it this would happen for you every time you utilise any of the menu items?
It seems to come from a pretty benign function openTabWithUrl... 

I will definitely check if that function should be changed.

Can you confirm that you are on  Mac OS X 10.14.6? I unfortunately no longer have a 10.14.6 machine, so it is a bit harder to check what might cause this. I had a look at App Store Connect and it doesn't list any Crash Reports there. I take it you did not opt in?

When you write other safari extensions produce similar crash logs, would you remember if anything in particular has changed at your end that would be common to this new unexpected behavior?

**Comment by gingerbeardman** [comment] 2020-01-27 19:06
Yes, every time I use the menu. I just used it now.

Yes, 10.14.6 Mojave.

I have opted in to crash reports, so that is odd.

No change in install or behaviour, though I am hovering around 50 tabs right now 😅

**Comment by otzbergnet** [comment] 2020-01-27 19:14
This is super strange. It previously worked for you, right? There were no updates to the app, so this is very strange.

I haven't really found any good source of information what to make of the crash report, I am a bit stumped right now. I will keep googling it, but I cannot think of what could go wrong.

This particular function simply gets the active window. it then ensures that I can create a URL and then asks that window to open the tab. It doesn't seem like it should cause a crash and yet, it does.

You mention you are at 50 tabs, I wonder, if Safari might be struggling for you. 8GB of RAM ain't a lot with this many tabs... Yet, it is a terrible answer.

**Comment by gingerbeardman** [comment] 2020-01-27 19:18
I'll get rid of some tabs and see if it happens

I wish I had a better Mac, sadly not :)

**Comment by otzbergnet** [comment] 2020-02-03 18:55
How are things on the error front? Were you able to see, if freeing up tabs (and thus memory) would help the situation? Many thanks in advance!

**Comment by gingerbeardman** [comment] 2020-02-03 22:28
It took a day or so for me to prune some tabs. During that day lots of crashes.

Since, hovering around 40 tabs, less frequent crashes.

[Archive.zip](https://github.com/otzbergnet/wbmExtension/files/4150512/Archive.zip)

Will find time to do proper clean room (tav save) exercise.

**Comment by otzbergnet** [comment] 2020-02-04 04:18
Hi Matt,

I took Safari to >50 tabs today on my 2012 iMac and was able to still use the Wayback Extension fine. I ought to admit that I have 16GB of ram in this machine, but I felt 53 was as many tabs as I could commit to this morning.

I am still not sure what would cause the crash that you are experiencing. I do however have one thought that I will pursue this weekend. Sadly, since I am not able to reproduce the problem, I'll need to ask you to test. Hope that's ok.

Claus

**Comment by gingerbeardman** [comment] 2020-02-04 09:10
Of course!

Accumulating this many tabs is an art that takes years to master. But you did well for a single morning!

**Comment by otzbergnet** [comment] 2020-11-21 18:06
fun fact, this has just reared its ugly head in my testing on macOS 11... :( So I'll spend a bit of time on this one

**Comment by otzbergnet** [comment] 2020-11-22 09:02
I made a small change with PR #29 that seems to have stopped the crashing behaviour. At least I was unable to recreate it since. Closing for now, but feel free to create a new issue, if the behavior were to return at your end

**Closed by otzbergnet** 2020-11-22 09:02 UTC
